"""
PDF report generator using ReportLab.
"""

import os
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle
from reportlab.lib.units import inch
from datetime import datetime


def generate_pdf_report(url: str, original_content: str, summary: str, output_path: str) -> str:
    """
    Generate a PDF report with original content and summary.

    Args:
        url: Source URL
        original_content: Original scraped text
        summary: AI-generated summary
        output_path: Path to save the PDF

    Returns:
        Path to the generated PDF file
    """
    doc = SimpleDocTemplate(
        output_path,
        pagesize=letter,
        rightMargin=72,
        leftMargin=72,
        topMargin=72,
        bottomMargin=72
    )

    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=18,
        spaceAfter=30,
        textColor=colors.darkblue
    )

    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=14,
        spaceBefore=20,
        spaceAfter=10,
        textColor=colors.darkblue
    )

    normal_style = ParagraphStyle(
        'CustomNormal',
        parent=styles['Normal'],
        fontSize=11,
        leading=14,
        spaceAfter=8
    )

    # Build story
    story = []

    # Title
    story.append(Paragraph("AI Workflow Automation Report", title_style))
    story.append(Spacer(1, 12))

    # Metadata
    metadata = f"""
    <b>Generated:</b> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}<br/>
    <b>Source URL:</b> <a href="{url}" color="blue">{url}</a><br/>
    <b>Original Content Length:</b> {len(original_content):,} characters
    """
    story.append(Paragraph(metadata, normal_style))
    story.append(Spacer(1, 30))

    # Summary section
    story.append(Paragraph("Executive Summary", heading_style))
    story.append(Spacer(1, 12))
    story.append(Paragraph(summary.replace('\n', '<br/>'), normal_style))
    story.append(Spacer(1, 30))

    # Original Content section
    story.append(Paragraph("Full Content", heading_style))
    story.append(Spacer(1, 12))

    # Split content into chunks to avoid overly long paragraphs
    max_chunk = 5000
    content_chunks = [original_content[i:i+max_chunk] for i in range(0, len(original_content), max_chunk)]

    for i, chunk in enumerate(content_chunks):
        if i > 0:
            story.append(PageBreak())
            story.append(Paragraph(f"Full Content (continued)", heading_style))
            story.append(Spacer(1, 12))
        story.append(Paragraph(chunk.replace('\n', '<br/>'), normal_style))

    # Footer
    story.append(Spacer(1, 30))
    footer = Paragraph(
        "Generated by AI Workflow Automation Demo | OpenClaw",
        ParagraphStyle('Footer', parent=styles['Normal'], fontSize=9, textColor=colors.grey)
    )
    story.append(footer)

    doc.build(story)
    return output_path
